# CMT folder: directory where you store cmt files
cmtfolder: "/ccs/home/lei/SOURCE_INVERSION/iter0/event_base/cmts"

# station folder
# setting different station files for different simulations(sources)
# station file should be named as: eventname.STATIONS
# for example: C200501121652A.STATIONS
stationfolder: "/ccs/home/lei/SOURCE_INVERSION/STATIONS"

# Size of your database. If you set the number to 10, then
# it means 10 copies of specfem will be copied. The runbase_size
# depends on how large disk size is since the model file is large
runbase_size: 50

# The large eventfile you want to split
total_eventfile: "/ccs/home/lei/SOURCE_INVERSION/iter0/event_base/inter.log.cmtlist"

# job sub-folder tag
job_tag: "si_inter"

# job running mode: "bundle" or "single"
# "bundle": bundle all forward simulation for one source in
#   one folder(preferred);
# "single": keep every single forward simulation in different
#   folder.
running_mode: "bundle"
# number of events in one pbs job
nevents_per_job: 1
# walltime for one forward simulation
walltime_per_simulation: 2

# Generate derivative CMTSOLUTION file
# If false, then you need to generate the derivative CMT
# externally(put them the same directory same as "cmtfolder")
# and then they will be copied in the job directory;
# If true, the derivative CMT will be generated internally.
generate_deriv_cmt: true
# Derive CMT list
# For example: ["Mrr", "Mtt", "Mpp", "Mrt", "Mrp", "Mtp", "dep", "lon", "lat"]
deriv_cmt_list: ["Mrr", "Mtt", "Mpp", "Mrt", "Mrp", "Mtp", "dep", "lon", "lat"]
# CMT perturbation
# Not used if "generate_deriv_cmt" is false
dmoment_tensor: 2.0e+23  # dyne * cm
ddepth: 3.0        # km
dlatitude: 0.03   # degree
dlongitude: 0.03   # degree
