# CMT folder: directory where you store cmt files
cmtfolder: "/ccs/home/lei/SOURCE_INVERSION/iter0/event_base/cmts"

# station folder
# setting different station files for different simulations(sources)
# station file should be named as: eventname.STATIONS
# for example: C200501121652A.STATIONS
stationfolder: "/ccs/home/lei/SOURCE_INVERSION/STATIONS"

---
# RUNBASE: the runbase is the directory where holds all running files
# So make sure that your runbase is large enough to hold everything
runbase: "/lustre/atlas/proj-shared/geo111/Wenjie/si_runbase"

# The large eventfile you want to split
total_eventfile: "inter.log.cmtlist"

# job sub-folder tag
job_tag: "si_inter_part1"

# job running mode: "simul"
# this branch only support simultaneous run, which means you use one mpirun to
# excute multiple simulation at the same time
running_mode: "simul"
# number of events in one job(with simultaneous run)
nevents_per_mpirun: 50
# walltime for one forward simulation(unit is minutes)
walltime_per_simulation: 12

---
# Generate derivative CMTSOLUTION file
# If false, then you need to generate the derivative CMT
# externally(put them the same directory same as "cmtfolder")
# and then they will be copied in the job directory;
# If true, the derivative CMT will be generated internally.
generate_deriv_cmt: true
# Derive CMT list
# For example: ["Mrr", "Mtt", "Mpp", "Mrt", "Mrp", "Mtp", "dep", "lon", "lat"]
deriv_cmt_list: ["Mrr", "Mtt", "Mpp", "Mrt", "Mrp", "Mtp", "dep", "lon", "lat"]
# CMT perturbation
# Not used if "generate_deriv_cmt" is false
dmoment_tensor: 2.0e+23  # dyne * cm
ddepth: 3.0        # km
dlatitude: 0.03   # degree
dlongitude: 0.03   # degree
