# CMT folder: directory where you store cmt files
cmtfolder: "../example_files/cmtcenter"

# Size of your database. If you set the number to 10, then
# it means 10 copies of specfem will be copied. The runbase_size 
# depends on how large disk size is since the model file is large
runbase_size: 50

# The large eventfile you want to split
total_eventfile: "../example_files/EVENTID_LIST"

# job sub-folder tag
job_tag: "test_benchmark"

# job running mode: "bundle" or "single"
# "bundle": bundle all forward simulation for one source in
#   one folder(preferred);
# "single": keep every single forward simulation in different
#   folder.
running_mode: "bundle"
# number of events in one pbs job
nevents_per_job: 1
# number of nodes used for on job
nnodes_per_simulation: 384
# walltime for one forward simulation
walltime_per_simulation: 2
